services:
  - docker

script:
  - docker-compose up couchbase -d
  - docker-compose run --publish 80:8100 golang make test
  - docker-compose down

notifications:
  email:
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
