services:
  - docker

script:
  - docker-compose up -d couchbase
  - docker-compose up golang
  - docker-compose down

notifications:
  email:
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
